export * from '../Pages/InicioPage'
export * from '../Pages/ContactosPage'
export * from '../Pages/NoticiasPage'
export * from '../Pages/QueHacemosPage'
export * from '../Pages/QuienesSomosPage'
export * from '../Pages/RepresentacionesPage'
